var courses = [{
    name: 'Trial Lesson',
    text: 'If you are interested in programming but not sure what type of coding then this is the lesson for you! In this lesson we ...',
    actText: 'If you are interested in programming but not sure what type of coding then this is the lesson for you!. In this lesson we will explore what you could do with coding and figure out the languages that are right for you. Try it out now because it is totally free. This is also a great way to get to know your awesome instructors!',
    languages: 'Breif overveiw',
    prequisites: 'None',
    otherApps: 'Simple Overlook',
    theme: '#ff403c',
    path: 'Completely Free!!',
    filterCat: 'other',
    geometricImage: '../../images/Trial.jpg',
    duration: '45 minutes',
    learn: ['The power of programming', 'Types of Programming', 'Different Code Editors', 'Choosing A Code Editor', 'Programming Languages'],

}, {
    name: 'HTML Course',
    text: 'HTML is the markup of all websites. It is needed to create text, images, videos, and much more on your websites. From Google to ...',
    actText: 'HTML is the markup of all websites. It is needed to create text, images, videos, and much more on your websites. From Google to any other small website, it all is some form of HTML to create the context of their websites. This will be the first step on your journey to becoming a web developer.',
    languages: 'HTML',
    prequisites: 'None',
    otherApps: 'None',
    theme: '#ff4c30',
    path: 'Skill',
    filterCat: 'skill',
    geometricImage: '../../images/HTML.jpg',
    duration: '6 - 10 weeks',
    learn: ['Intro to programming', 'Choosing a Code Editors', 'Basic HTML', 'How HTML is Used', 'Advanced HTML', 'Other languages to learn', 'Includes: support and review material'],
}, {
    name: 'CSS Course',
    text: 'Create attractive and eye catching websites an pages that will impress everyone with CSS. This course will teach you how to ...',
    actText: 'Create attractive and eye catching websites an pages that will impress everyone with CSS. This course will teach you how to use complex CSS concepts and use them to create styles that come right out of your mind. One of the most important steps in creating attrctive and responsive websites is learning CSS!</i>',
    languages: 'CSS',
    prequisites: 'HTML',
    otherApps: 'Pixlr (Basic Photo Editing)',
    theme: '#40c3ff',
    path: 'Skill',
    filterCat: 'skill',
    geometricImage: '../../images/CSS.jpg',
    duration: '6 - 10 weeks',
    learn: ['The power of Styling', 'CSS terms & Formatting', 'Basic CSS', 'CSS Conspts: Flexbox, media queries ...', 'Advanced CSS', 'Other languages to learn', 'Includes: support and review material'],
}, {
    name: 'HTML and CSS',
    text: 'By taking this course you will be able to create a beautiful website that can adapt to any device. You will be able to construct a...',
    actText: 'By taking this course you will be able to create a beautiful website that can adapt to any device. You will be able to construct a responsive and attractive website. You can make your website look cool, dynamic, classic, modern, colorful or anything else that you want.',
    languages: 'HTML, CSS',
    prequisites: 'None',
    otherApps: 'Pixlr (Basic Photo Editing)',
    theme: '#dd29d4',
    path: 'Skill',
    filterCat: 'skill',
    geometricImage: '../../images/HTML-CSS.jpg',
    duration: '10 - 16 weeks',
    learn: ['Intro to programming', 'Choosing a Code Editors', 'Basic HTML', 'How HTML is Used', 'Advanced HTML', 'The power of Styling', 'CSS terms & Formatting', 'Basic CSS', 'CSS Conspts: Flexbox, media queries ...', 'Advanced CSS', 'Other languages to learn', 'Includes: support and review material'],
}, {
    name: 'JavaScript Course',
    text: 'In this course you will learn the language that makes most websites interactive. By learning this language you will...',
    actText: 'In this course you will learn the language that makes most websites interactive. By learning this language you will be able to do things that you have never even imagined you could with your website. Once you have learned this language, you will be able to create games and cool effects.',
    languages: 'Breif overveiw',
    prequisites: 'Basic HTML',
    otherApps: 'None',
    theme: '#fed330',
    path: 'Skill',
    filterCat: 'skill',
    geometricImage: '../../images/JavaScript.jpg',
    duration: '8 - 10 weeks',
    learn: ['Javascripts power', 'Basic Javascript: Variables, Arrays...', 'Javascript Projects and Problems', 'More Advanced Javascript', 'Includes: support and review material'],
}, {
    name: 'Terminal Course',
    text: 'Learn how to operate the terminal by using bash. It is a very important aspect in coding or just if you want to learn about your device. The terminal is a place where you can control...',
    actText: 'Learn how to operate the terminal by using bash. It is a very important aspect in coding or just if you want to learn about your device. The terminal is a place where you can control your device\'s files.The terminal is an important asset in coding.In this course you will also learn how to use Git.Git is a place where you can share files or where two people can work on the same project on two different devices!',
    languages: 'Bash',
    prequisites: 'None',
    otherApps: 'Git',
    theme: '#26de81',
    path: 'Skill',
    filterCat: 'skill',
    geometricImage: '../../images/Terminal.jpg',
    duration: '3-5 weeks',
    learn: ['What Coding Can Do', 'Types of Coding', 'Code Editors', 'Downloading A Code Editor', 'Coding Languages'],
}, {
    name: 'Web Development',
    text: 'In this course you will learn how to become a top tier developer. It includes everything you need to know to build an interactive and responsive website. In this course you will learn...',
    actText: 'In this course you will learn how to become a top tier developer. It includes everything you need to know to build an interactive and responsive website. In this course you will learn how to code in HTML, CSS, and JavaScript, you will also learn how to use git and to operate the terminal. After finishing this course you will be able to awe people with your coding skills.',
    languages: 'Breif overveiw',
    prequisites: 'HTML, CSS, JavaScript',
    otherApps: 'Breif Overveiw',
    theme: '#0fb9b1',
    filterCat: 'career',
    path: 'Career',
    duration: '45 minutes',
    learn: ['What Coding Can Do', 'Types of Coding', 'Code Editors', 'Downloading A Code Editor', 'Coding Languages'],
}, {
    name: 'Tech Course',
    text: 'In this course you will become efficient with technology. You will also learn things you thought you can’t do with your device like...',
    actText: 'In this course you will become efficient with technology. You will also learn things you thought you can’t do with applications like Zoom, Google Meets, Google Drive, etc.. Once you have finished this course, you won’t have to ask for any tech help and instead you will be the one giving others tech help!',
    languages: 'Breif overveiw',
    prequisites: 'HTML, CSS, JavaScript',
    otherApps: 'Breif Overveiw',
    theme: '#B33771',
    filterCat: 'skill',
    path: 'Skill',
    duration: '45 minutes',
    learn: ['What Coding Can Do', 'Types of Coding', 'Code Editors', 'Downloading A Code Editor', 'Coding Languages'],
}]