var team = [{
    name: 'Koshik Kumaravel',
    img: 'koshik.jpg',
    position: 'Chief Executive Officer and President',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam impedit nemo laboriosam facilis et est, ipsum veniam placeat ipsa nisi totam mollitia nulla, omnis ad voluptate reprehenderit cumque? Debitis sed expedita minima cumqueillo, velit iusto cupiditate assumenda, mollitia quos corporis omnis, porro dolores quas suscipit cum? Saepe id, hic atque fuga at necessitatibus doloribus eveniet aliquam harum mollitia consequatur maiores rem ex aperiam quiatotam temporibus excepturi! Officia hic eligendi porro architecto cumque at voluptates fugiat? Facere beatae nostrum et porro hic est, optio assumenda, soluta laborum velit quisquam iure corporis ipsum quod magni adipisci quibusdamcupiditate consequatur dignissimos?<br><br>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique consequuntur sit nobis consectetur eveniet cupiditate sequi iure explicabo excepturi eaque saepe, voluptatem accusantiumodio cumque? Maxime odio debitis numquam officiis praesentium, quo aliquam obcaecati temporibus ex eaque ratione vero reprehenderit omnis laborum! Blanditiis quo inventore perspiciatis fugit? Cumque, quae ex.'
}, {
    name: 'Inesh Kumaravel',
    img: 'inesh.jpg',
    position: 'Chief Operating Officer and Vice President',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam impedit nemo laboriosam facilis et est, ipsum veniam placeat ipsa nisi totam mollitia nulla, omnis ad voluptate reprehenderit cumque? Debitis sed expedita minima cumqueillo, velit iusto cupiditate assumenda, mollitia quos corporis omnis, porro dolores quas suscipit cum? Saepe id, hic atque fuga at necessitatibus doloribus eveniet aliquam harum mollitia consequatur maiores rem ex aperiam quiatotam temporibus excepturi! Officia hic eligendi porro architecto cumque at voluptates fugiat? Facere beatae nostrum et porro hic est, optio assumenda, soluta laborum velit quisquam iure corporis ipsum quod magni adipisci quibusdamcupiditate consequatur dignissimos?<br><br>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique consequuntur sit nobis consectetur eveniet cupiditate sequi iure explicabo excepturi eaque saepe, voluptatem accusantiumodio cumque? Maxime odio debitis numquam officiis praesentium, quo aliquam obcaecati temporibus ex eaque ratione vero reprehenderit omnis laborum! Blanditiis quo inventore perspiciatis fugit? Cumque, quae ex.'
}]