var courses = [{
    name: 'Trial Lesson',
    image: '../../images/bg.jpg',
    text: 'If you are interested in coding but not sure what type of coding then take this lesson. In this lesson we will explore what you could do with coding...',
    actText: 'If you are interested in coding but not sure what type of coding then take this lesson. In this lesson we will explore what you could do with coding and figure out the language that is right for you. Try it out now because it is totally free.',
    languages: 'Breif overveiw',
    otherApps: 'Breif Overveiw',
    theme: '#ff403c',
    path: 'Skill',
    duration: '45 minutes',
    learn: ['What Coding Can Do', 'Types of Coding', 'Code Editors', 'Downloading A Code Editor', 'Coding Languages'],

}, {
    name: 'HTML Course',
    image: '../../images/bg.jpg',
    text: 'In this course you will learn one of the easiest and needed coding languages for all websites: HTML. Most websites use it, from google...',
    actText: 'In this course you will learn one of the easiest and needed coding languages for all websites: HTML. Most websites use it, from google to safari. Once you master this course you will be able to be the builder of websites.',
    languages: 'Breif overveiw',
    otherApps: 'Breif Overveiw',
    theme: '#ff4c30',
    path: 'Skill',
    duration: '45 minutes',
    learn: ['What Coding Can Do', 'Types of Coding', 'Code Editors', 'Downloading A Code Editor', 'Coding Languages'],
}, {
    name: 'CSS Course',
    image: '../../images/bg.jpg',
    text: 'In this course you will learn the most used styling language: CSS. CSS is what most websites use and if they don’t they use a version of CSS. CSS is...',
    actText: 'In this course you will learn the most used styling language: CSS. CSS is what most websites use and if they don’t they use a version of CSS. CSS is the artist of most websites and gives the website the styling it needs to look cool or classic. You can add cool animations that make things spin, change color and a lot of other stuff. <strong><u>NOTE:</u></strong><i>You can only use CSS if you have at least a little basic HTML knowledge.</i>',
    languages: 'Breif overveiw',
    otherApps: 'Breif Overveiw',
    theme: '#40c3ff',
    path: 'Skill',
    duration: '45 minutes',
    learn: ['What Coding Can Do', 'Types of Coding', 'Code Editors', 'Downloading A Code Editor', 'Coding Languages'],
}, {
    name: 'HTML and CSS',
    image: '../../images/bg.jpg',
    text: 'By taking this course you will be able to create a beautiful website that can adapt to any device. You will be able to construct a...',
    actText: 'By taking this course you will be able to create a beautiful website that can adapt to any device. You will be able to construct a responsive website. You can make your website look cool, dynamic, classic, or anything you want.',
    languages: 'Breif overveiw',
    otherApps: 'Breif Overveiw',
    theme: '#dd29d4',
    path: 'Skill',
    duration: '45 minutes',
    learn: ['What Coding Can Do', 'Types of Coding', 'Code Editors', 'Downloading A Code Editor', 'Coding Languages'],
}, {
    name: 'JavaScript Course',
    image: '../../images/bg.jpg',
    text: 'In this course you will learn the language that makes most websites interactive. By learning this language you will...',
    actText: 'In this course you will learn the language that makes most websites interactive. By learning this language you will be able to do things that you have never even imagined you could with your website. Once you have learned this language, you will be able to create games and cool effects.',
    languages: 'Breif overveiw',
    otherApps: 'Breif Overveiw',
    theme: '#fed330',
    path: 'Skill',
    duration: '45 minutes',
    learn: ['What Coding Can Do', 'Types of Coding', 'Code Editors', 'Downloading A Code Editor', 'Coding Languages'],
}, {
    name: 'Terminal Course',
    image: '../../images/bg.jpg',
    text: 'Learn how to operate the terminal by using bash. It is a very important aspect in coding or just if you want to learn about your device. The terminal is a place where you can control...',
    actText: 'Learn how to operate the terminal by using bash. It is a very important aspect in coding or just if you want to learn about your device. The terminal is a place where you can control your device\'s files.The terminal is an important asset in coding.In this course you will also learn how to use Git.Git is a place where you can share files or where two people can work on the same project on two different devices!',
    languages: 'Bash',
    otherApps: 'Git',
    theme: '#26de81',
    path: 'Skill',
    duration: '45 minutes',
    learn: ['What Coding Can Do', 'Types of Coding', 'Code Editors', 'Downloading A Code Editor', 'Coding Languages'],
}, {
    name: 'Web Development',
    image: '../../images/bg.jpg',
    text: 'In this course you will learn how to become a top tier developer. It includes everything you need to know to build an interactive and responsive website. In this course you will learn...',
    actText: 'In this course you will learn how to become a top tier developer. It includes everything you need to know to build an interactive and responsive website. In this course you will learn how to code in HTML, CSS, and JavaScript, you will also learn how to use git and to operate the terminal. After finishing this course you will be able to awe people with your coding skills.',
    languages: 'Breif overveiw',
    otherApps: 'Breif Overveiw',
    theme: '#0fb9b1',
    path: 'Career',
    duration: '45 minutes',
    learn: ['What Coding Can Do', 'Types of Coding', 'Code Editors', 'Downloading A Code Editor', 'Coding Languages'],
}, {
    name: 'Tech Course',
    image: '../../images/bg.jpg',
    text: 'In this course you will become efficient with technology. You will also learn things you thought you can’t do with your device like...',
    actText: 'In this course you will become efficient with technology. You will also learn things you thought you can’t do with applications like Zoom, Google Meets, Google Drive, etc.. Once you have finished this course, you won’t have to ask for any tech help and instead you will be the one giving others tech help!',
    languages: 'Breif overveiw',
    otherApps: 'Breif Overveiw',
    theme: '#B33771',
    path: 'Skill',
    duration: '45 minutes',
    learn: ['What Coding Can Do', 'Types of Coding', 'Code Editors', 'Downloading A Code Editor', 'Coding Languages'],
}]